force-app/main/default/objects/Contact/fields/Normalised_Email__c.field-meta.xml
<CustomField>
    <fullName>Normalised_Email__c</fullName>
    <description>Normalised version of the contact email field to help identify duplicate contacts</description>
    <formula>IF(ISBLANK(Email), NULL, LOWER(Email))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Normalised version of the contact email field to help identify duplicate contacts</inlineHelpText>
    <label>Normalised Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Normalised_Phone__c.field-meta.xml
<CustomField>
    <fullName>Normalised_Phone__c</fullName>
    <description>Normalised version of the contact phone field to help identify duplicate contacts</description>
    <formula>IF(
    ISBLANK(Phone),
    NULL,
    SUBSTITUTE(
        SUBSTITUTE(
        SUBSTITUTE(
        SUBSTITUTE(
        SUBSTITUTE(
        SUBSTITUTE(Phone,&quot; &quot;,&quot;&quot;),
        &quot;-&quot;,&quot;&quot;),
        &quot;(&quot;,&quot;&quot;),
        &quot;)&quot;,&quot;&quot;),
        &quot;+&quot;,&quot;&quot;),
        &quot;.&quot;,&quot;&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Normalised version of the contact phone field to help identify duplicate contacts</inlineHelpText>
    <label>Normalised Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactDuplicateController.cls
public with sharing class ContactDuplicateController {
    
    @AuraEnabled(cacheable=true)
    public static List<Contact> getDuplicateContacts(Id recordId) {
        Contact contact = [SELECT Id, Normalised_Email__c, Normalised_Phone__c FROM Contact WHERE Id = :recordId WITH SECURITY_ENFORCED];
        List<Contact> contacts = new List<Contact>();
        if (contact.Normalised_Email__c != null && contact.Normalised_Phone__c != null) {
            contacts = [SELECT Id, Email, Phone, Name FROM Contact WHERE (Normalised_Email__c != null OR Normalised_Phone__c != null) AND (Normalised_Email__c = :contact.Normalised_Email__c OR Normalised_Phone__c = :contact.Normalised_Phone__c) AND Id != :recordId WITH SECURITY_ENFORCED ORDER BY CreatedDate DESC];
        }
        return contacts;
    }

}